CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE "Administrateur" (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    "Nom" varchar(255) NOT NULL UNIQUE,
    "Mot_de_passe" text NOT NULL
);

CREATE TABLE "Passager" (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now(),
    "Nom" varchar(255) NOT NULL UNIQUE,
    "Pseudo" varchar(255),
    "Numero" varchar(50) NOT NULL UNIQUE,
    "Email" varchar(255) NOT NULL UNIQUE,
    "Mot_de_passe" text NOT NULL
);